import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "../components/providers";
import Navbar from "@/components/Layout/Navbar";
import { Inter, Roboto } from "next/font/google";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type props = { children: React.ReactNode };
export default function RootLayout({ children }: props) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
